# mkdocs.yml
site_name: wandb-addons

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select

plugins:
  - mkdocstrings
  - search
  - minify
  - glightbox


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
    alternate_style: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'
  - 'Ciclo': 'ciclo.md'
  - 'MonAI': 'monai.md'
  - 'Utils': 'utils.md'