name: Deploy
on:
  push:
    branches:
      - release
permissions:
  contents: write
  id-token: write

jobs:
  # documentation:
  #   name: Update Docuementation on GitHub Pages
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.x
  #     - uses: actions/cache@v2
  #       with:
  #         key: ${{ github.ref }}
  #         path: .cache
  #     - run: pip install .[docs]
  #     - run: mkdocs gh-deploy --force
  
  pypi-publish:
    name: Upload release to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.5
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PIPY_API_KEY }}