name: Run Tests
on:
  pull_request:
    paths:
      - .github/**
      - wandb_addons/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  run-monai-tests:
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
    container: tensorflow/tensorflow
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U pip
          pip install -e .[monai]
          python -c "from wandb_addons.monai import WandbStatsHandler"