name: Run Tests
on:
  pull_request:
    paths:
      - .github/**
      - wandb_addons/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  run-monai-tests:
    runs-on: ubuntu-latest
    container: projectmonai/monai
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U pip
          pip install .[monai]
          python -c "from wandb_addons.monai import WandbStatsHandler"
  
  run-keras-tests:
    runs-on: ubuntu-latest
    container: tensorflow/tensorflow
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U pip
          pip install .[keras]
          python -c "import tensorflow as tf"
  
  run-jax-tests:
    runs-on: ubuntu-latest
    container: python
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U pip
          pip install .[jax]
          python -c "from wandb_addons.ciclo import wandb_logging"